apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: nodejs
        ports:
        - containerPort: 8082
        env:
        - name: ME_CONFIG_POSTGRES_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-root-username
        - name: ME_CONFIG_POSTGRES_ADMINPASSWORD
          valueFrom: 
            secretKeyRef:
              name: postgres-secret
              key: postgres-root-password
        - name: ME_CONFIG_POSTGRES_SERVER
          valueFrom: 
            configMapKeyRef:
              name: postgres-configmap
              key: POSTGRES_url
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30001
